# Generated by Django 2.1.2 on 2018-10-15 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nanowrimo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ('title',)},
        ),
        migrations.AlterModelOptions(
            name='chapter',
            options={'ordering': ('number',)},
        ),
        migrations.AlterModelOptions(
            name='character',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='place',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='prop',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='scene',
            options={'ordering': ('short_description',)},
        ),
        migrations.AddField(
            model_name='scene',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='inventoryexchange',
            name='prop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchanges', to='nanowrimo.Prop'),
        ),
        migrations.AlterField(
            model_name='inventoryexchange',
            name='scene',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchanges', to='nanowrimo.Scene'),
        ),
        migrations.AlterField(
            model_name='scene',
            name='characters',
            field=models.ManyToManyField(blank=True, related_name='scenes', to='nanowrimo.Character'),
        ),
    ]
